services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: bookstore-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-bookstore_db}
      MYSQL_USER: ${MYSQL_USER:-bookstore}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-bookstore123}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - bookstore-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 60s

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runtime
    container_name: bookstore-backend-dev
    restart: unless-stopped
    environment:
      # Database configuration
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE:-bookstore_db}
      DB_USERNAME: ${MYSQL_USER:-bookstore}
      DB_PASSWORD: ${MYSQL_PASSWORD:-bookstore123}
      
      # MySQL database configuration with explicit password  
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/bookstore_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "bookstore"
      SPRING_DATASOURCE_PASSWORD: "bookstore123"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
      
      # Disable Flyway for now
      SPRING_FLYWAY_ENABLED: "false"
      
      # JPA Configuration  
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.MySQLDialect"
      
      # Spring profiles - use default application.properties
      SPRING_PROFILES_ACTIVE: ""
      
      # JVM settings
      JAVA_OPTS: >-
        -Xms256m 
        -Xmx512m 
        -XX:+UseContainerSupport 
        -XX:MaxRAMPercentage=75.0
        
      # Application settings
      SERVER_PORT: 8080
      MANAGEMENT_SERVER_PORT: 8081
      
      # Logging
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_COM_EXAMPLE_BOOKSTORE: DEBUG
    ports:
      - "${BACKEND_PORT:-8080}:8080"
      - "${BACKEND_MGMT_PORT:-8081}:8081"
    volumes:
      - backend_logs:/app/logs
    networks:
      - bookstore-network
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/app/health-check.sh"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 60s

volumes:
  mysql_data:
    driver: local
  backend_logs:
    driver: local

networks:
  bookstore-network:
    driver: bridge